CREATE TABLE album (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
artist VARCHAR(255) NOT NULL,
year SMALLINT(4),
imglocation VARCHAR(500) DEFAULT 'resources/images/album_black_48dp.png'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;